### ISSUE TITLE
Black and White

### ISSUE THREAD

**Issue by erwindenboer** [StefanNienhuis/MMM-Buienradar#4]
@StefanNienhuis Love the module! But the overall look and feel of the MagicMirror is black and white. With a colored picture this doesn't look like it fits in. Could an option be made which toggles between colored and a black and white version of this module? Thanks in advance!

**Comment by daveerken** [comment]
I don't think it's possible since the images are pulled directly from the buienradar site.

Maybe you can add a little color to the other modules? 
that's what i did and now it is more aesthetically pleasing

**Comment by StefanNienhuis** [comment]
Sorry @erwindenboer, I forgot about your issue, as I don't use MagicMirror myself anymore. I just implemented a 'monochrome' config paramater with 12596fd.
