### ISSUE TITLE
Fantastically helpfull, but unscallable.

### ISSUE THREAD

**Issue by Bernard-h** [StefanNienhuis/MMM-Buienradar#5]
Hi Stephan, thank you for your contribution. Ik vind het geweldig.
I have many modules (in multiple carousels) simply because there is much info on need on my mirror.

Is it possible to add a parameter to set max width and max height op the map. that would be VERY VERY helpfull

**Comment by Brtrnd** [comment]
Hi, I don't know how to upload, but I've added the sizes as Buienradar offers them.
https://www.buienradar.nl/overbuienradar/gratis-weerdata

I've added a config property iSize. it can be small,medium,large,extralarge
it will default to medium

[MMM-Buienradar.js.txt](https://github.com/StefanNienhuis/MMM-Buienradar/files/6215594/MMM-Buienradar.js.txt)
[MMM-Buienradar.css.txt](https://github.com/StefanNienhuis/MMM-Buienradar/files/6215595/MMM-Buienradar.css.txt)

**Comment by Bernard-h** [comment]
Hi Brtrnd, can you tel me exactly where to go / do ? Do I just replace the 2 files with the one posted above and edit the .ccs.txt?
Thanks in advance.  
(very close to closing topic)

**Comment by Brtrnd** [comment]
if this works, download and overwrite the existing files with these ones
(css) https://raw.githubusercontent.com/StefanNienhuis/MMM-Buienradar/a30e45eef22c7762e9037612523fa91f7954bed2/MMM-Buienradar.css
(js) https://raw.githubusercontent.com/StefanNienhuis/MMM-Buienradar/a30e45eef22c7762e9037612523fa91f7954bed2/MMM-Buienradar.js

if that doesn't work, go to https://github.com/StefanNienhuis/MMM-Buienradar/pull/2/files
on the right you see a checkbox with viewed and 3 dots...
click on the dots, click on view file 
download the file
and overwrite the existing ones

**Comment by Bernard-h** [comment]
Clear as a bell , thank you for your help. closing topic.

**Comment by hannesjust** [comment]
Hallo ich habe das Modul auch installiert nach Anweisung, aber es erscheint kein Bild auf dem Monitor, was mache ich falsch
